### PR TITLE
Repaired off by one check for rate limits

### PR DESCRIPTION
**Pull request by twolfson**
As discussed in #20, the rate limiter has an off by one error by counting too early. This PR repairs that by adding a `GET` check before performing an increment (which is also more efficient). Additionally, the examples provided by the Redis docs agree that this is the proper approach:

http://redis.io/commands/incr#pattern-rate-limiter

Additional changes that came in this PR:

- Removed `pipeline` from being defined via `__init__`
    - Since we are using a `.get()` during `.update()`, starting a multi statement only to immediate run exec is inefficient. As a result, we create the `pipeline` in `update()` over `__init__`

In this PR:

- Updated tests to account for off by one error
- Added regression assertion to verify we never exceed limit in our tests
- Added fix for off by one error
- Renamed to `self.cache` for consistency between backends and removed `self.pipeline` creation

### CODE REVIEW

**Comment by jirikuncar** [comment]
@twolfson thanks for your improvements and fixes. I have fixed the Travis CI issues in #23 so can you please rebase your branch and (force) re-push?

- [ ] Please add yourself to `AUTHORS`.
- [ ] Please reply if you agree to donate this (and any future) contributions to *Flask-Ratelimiter* package under the terms of the Revised BSD Licence.

Finally, we are trying to keep our commit messages in common style across Invenio Software projects so we can automatically generate RELEASE-NOTES. Can you please amend your commit message in similar way:

**Example**
```
redis: fix off-by-one check

* FIX Adds fix for off-by-one error.

* INCOMPATIBLE Renames `self.redis` to `self.cache` for consistency
  between backends.

* BETTER ... # FIXME explain why it is better to do the `pipeline` creation during update

Reviewed-by: Jiri Kuncar <jiri.kuncar@cern.ch>
Signed-off-by: # FIXME add your name and email
```

**Comment by twolfson** [comment]
@jirikuncar I have taken care of the requested notes (e.g. `AUTHORS`, `git commit`). Additionally, I transfer my contributions for this and future pull requests to the maintainers of this repository under the existing Revised BSD License.

**Comment by twolfson** [comment]
There was an uncaught bug in the Python3 tests. I have patched it up:

```python
        # In Python 3, this is bytes not a string
        self.assertEqual(self.redis.get(keys[0]), '3')
 
        # Working fix
        self.assertEqual(self.redis.get(keys[0]).decode('utf-8'), '3')
```

**Comment by jirikuncar** [comment]
@twolfson thanks! Let me please re-phrase the last bullet:

```
* BETTER Adds `self.cache.get()` to `update` for backends and
  moves `pipeline()` from `__init__` inside  `update` to use single 
  source for all calls and reduce excess calls for any `.get()`
  (e.g. don't need `MULTI` and `EXEC` for a `GET`).
```

**Comment by twolfson** [comment]
Done :+1:

**Comment by jirikuncar** [comment]
:rocket:

**Comment by twolfson** [comment]
Woo hoo!

**Pull request merged**
