### PR TITLE
Bugfix for dynamic limits, test added

### PR DESCRIPTION
**Pull request by vsudilov**
Hi,

It seems that `RateLimitInfo` should be passed `current_limit` instead of `limit`. If `limit` is callable, then `RateLimitInfo` will be given the string representation of that callable and not its return value - this PR should fix that. 

Also added a test for dynamic rate limits

### CODE REVIEW

**Comment by jirikuncar** [comment]
Hello @vsudilov,
can you please rebase your commit on top of latest `master` branch and while doing it please amend commit message to follow our style:

```
limitter: pass current_limit instead of limit

* Addresses issue with `RateLimitInfo` when `limit` is callable. Passing
  `current_limit` instead of `limit` fixes this odd behavior.
```

Thanks a lot :+1:

**Comment by vsudilov** [comment]
Hi @jirikuncar , 

I think I made some mistake --I rebased locally to get rid of the `git pull upstream master` merge commit, then pushed and made the PR. I didn't realize that the old commits would show up again as new items in the history, sorry about that.

Unless you have a better solution, I suggest to close this PR and let me make a new PR based on a new fork.

ps - Thanks for the tip, but it doesn't work -- only `cbb8` and `fda9` are available in `git rebase -i upstream/master`

**Comment by jirikuncar** [comment]
```
git checkout -b patch master
git checkout master
git reset --hard upstream/master
git checkout patch
git rebase -i master
git checkout master
git merge --ff-only patch
git push origin master -f
```

**Comment by vsudilov** [comment]
No dice; rebase -i still only shows cbb8 and fda9. I'll re-do with a new fork now ;)

**Pull request closed without merging**
